---
abstract: 'A bundle of Catmandu modules for working with data from EuropePMC'
author:
  - 'Vitali Peil'
build_requires:
  Module::Build: 0.3601
  Test::Exception: 0.32
  Test::More: 0.88
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catmandu-EuropePMC
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Catmandu: 0
  Catmandu::XML: 0
  Furl: 0
  Moo: 0
  Try::Tiny: 0
  perl: v5.10.1
resources:
  bugtracker: https://github.com/LibreCat/Catmandu-EuropePMC/issues
  homepage: https://github.com/LibreCat/Catmandu-EuropePMC
  repository: https://github.com/LibreCat/Catmandu-EuropePMC.git
version: 0.15
x_contributors:
  - 'vpeil <vitali.peil@uni-bielefeld.de>'
